name: First Workflow

on: 
    push:
    pull_request:
        branches:
            - develop
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
        
            - name: Setup Node.js in VM
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci
            
            - name: Run ESlint
              run: npm run lint

            - name: make react build
              run: npm run build