name: Main Workflow

on: 
    push:
    pull_request:
        branches:
            - develop
jobs:
    lint-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
        
            - name: Setup Node.js in VM
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci
            
            - name: Run ESlint
              run: npm run lint

    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
        
            - name: Setup Node.js in VM
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run test cases
              run: npm run test

            
    build-job:
        needs: [lint-job,test-job]
        runs-on: ubuntu-latest

        env:
            VERCEL_ORG_ID: "${{ secrets.VERCEL_ORG_ID }}"
            VERCEL_PROJECT_ID: "${{ secrets.VERCEL_PROJECT_ID}}"
            
        steps:
            - name: checkout
              uses: actions/checkout@v4
        
            - name: Setup Node.js in VM
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: make react build
              run: npm run build

            - name: create artifact
              uses: actions/upload-artifact@v4
              with:
                  name: react-build
                  path: dist/
                  retention-days: 5
            - name: "Install vercel"
              run: npm install -g vercel

            - name: "Deployment on Vercel"
              run: vercel deploy dist --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
        
           